name: Build static site to root folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build estático do Next.js
        run: npm run build

      - name: Mover build para a root
        run: |
          shopt -s dotglob
          rm -rf !(out|.git|.github)
          mv out/* .
          mv out/.* . 2>/dev/null || true
          rmdir out
          touch .nojekyll

      - name: Commit e push do build
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualizar site estático na root" || echo "Sem alterações"
          git push 